export const JOB_TYPES = [
  'Software Engineering',
  'Frontend Development',
  'Backend Development',
  'Full Stack Development',
  'Mobile Development',
  'Machine Learning',
  'Data Science',
  'Data Engineering',
  'Quantitative Finance',
  'Investment Banking',
  'Private Equity',
  'Finance',
  'Consulting',
  'Accounting',
  'Research',
  'Security Engineering',
  'DevOps',
  'Quality Assurance',
  'Hardware Engineering',
  'Embedded Systems',
  'Robotics',
  'Product Management',
  'UI/UX Design',
  'Marketing',
  'Sales',
  'Operations',
  'Human Resources',
];

export const JOB_TYPE_KEYWORDS: Record<string, (string | RegExp)[]> = {
  'Software Engineering': [
    /software engineer/i,
    /software engineering/i,
    /software developer/i,
    /\bswe\b/i,
    /engineer(?:ing)?\s+(?:intern|co-?op)/i,
    /developer\s+(?:intern|co-?op)/i,
  ],
  'Frontend Development': [
    /front[-\s]?end/i,
    /frontend/i,
    /web developer/i,
    /ui engineer/i,
    /javascript developer/i,
  ],
  'Backend Development': [
    /back[-\s]?end/i,
    /backend/i,
    /server engineer/i,
    /api developer/i,
    /platform engineer/i,
  ],
  'Full Stack Development': [/full[-\s]?stack/i, /fullstack/i],
  'Mobile Development': [
    /mobile/i,
    /\bios\b/i,
    /android/i,
    /react native/i,
    /swift/i,
    /kotlin/i,
  ],
  'Machine Learning': [
    /machine learning/i,
    /\bml\b/i,
    /deep learning/i,
    /computer vision/i,
    /artificial intelligence/i,
  ],
  'Data Science': [
    /data science/i,
    /data scientist/i,
    /data analytics/i,
    /data analyst/i,
    /business intelligence/i,
  ],
  'Data Engineering': [
    /data engineer/i,
    /data engineering/i,
    /analytics engineer/i,
    /data platform/i,
    /data pipeline/i,
  ],
  'Quantitative Finance': [
    /quantitative/i,
    /\bquant\b/i,
    /algorithmic trading/i,
    /trading analyst/i,
    /derivatives/i,
    /quant finance/i,
  ],
  'Research': [
    /research scientist/i,
    /research engineer/i,
    /research internship/i,
    /r&d/i,
  ],
  'Security Engineering': [
    /security engineer/i,
    /cybersecurity/i,
    /information security/i,
    /appsec/i,
  ],
  'DevOps': [
    /devops/i,
    /site reliability/i,
    /\bsre\b/i,
    /infrastructure/i,
    /cloud engineer/i,
    /platform reliability/i,
    /release engineer/i,
  ],
  'Quality Assurance': [
    /\bqa\b/i,
    /quality assurance/i,
    /test engineer/i,
    /testing engineer/i,
    /automation engineer/i,
  ],
  'Hardware Engineering': [
    /hardware engineer/i,
    /electrical engineer/i,
    /electronics engineer/i,
    /asic/i,
    /fpga/i,
    /semiconductor/i,
    /chip design/i,
  ],
  'Embedded Systems': [
    /embedded engineer/i,
    /embedded systems/i,
    /firmware/i,
    /\biot\b/i,
    /real-time systems/i,
  ],
  'Robotics': [
    /robotics/i,
    /robotic engineer/i,
    /autonomous systems/i,
    /mechatronics/i,
  ],
  'Product Management': [
    /product manager/i,
    /product management/i,
    /product strategy/i,
  ],
  'UI/UX Design': [
    /user experience/i,
    /user interface/i,
    /ux design/i,
    /ui design/i,
    /product design/i,
    /interaction design/i,
  ],
  'Investment Banking': [
    /investment banking/i,
    /\bib\b/i,
    /mergers and acquisitions/i,
    /\bm&a\b/i,
    /corporate finance/i,
    /capital markets/i,
    /equity research/i,
  ],
  'Private Equity': [
    /private equity/i,
    /\bpe\b(?!\s*engineer)/i,
    /growth equity/i,
    /venture capital/i,
    /\bvc\b/i,
  ],
  'Finance': [
    /financial analyst/i,
    /finance analyst/i,
    /treasury/i,
    /fp&a/i,
    /financial planning/i,
  ],
  'Consulting': [
    /management consulting/i,
    /strategy consulting/i,
    /business consulting/i,
    /consultant/i,
    /advisory/i,
  ],
  'Accounting': [
    /accounting/i,
    /audit/i,
    /tax/i,
    /financial reporting/i,
    /cpa/i,
  ],
  'Marketing': [
    /marketing/i,
    /brand management/i,
    /digital marketing/i,
    /growth marketing/i,
    /content marketing/i,
    /marketing analytics/i,
  ],
  'Sales': [
    /sales development/i,
    /\bsdr\b/i,
    /business development/i,
    /\bbdr\b/i,
    /account management/i,
    /sales operations/i,
  ],
  'Operations': [
    /operations/i,
    /supply chain/i,
    /logistics/i,
    /process improvement/i,
    /business operations/i,
  ],
  'Human Resources': [
    /human resources/i,
    /\bhr\b/i,
    /people operations/i,
    /recruiting/i,
    /talent acquisition/i,
  ],
};
