export const JOB_TYPES = [
  'Software Engineering',
  'Frontend Development',
  'Backend Development',
  'Full Stack Development',
  'Mobile Development',
  'Machine Learning',
  'Data Science',
  'Data Engineering',
  'Quantitative Finance',
  'Research',
  'Security Engineering',
  'DevOps',
  'Quality Assurance',
  'Hardware Engineering',
  'Embedded Systems',
  'Robotics',
  'Product Management',
  'UI/UX Design',
];

export const JOB_TYPE_KEYWORDS: Record<string, (string | RegExp)[]> = {
  'Software Engineering': [
    /software engineer/i,
    /software engineering/i,
    /software developer/i,
    /\bswe\b/i,
  ],
  'Frontend Development': [
    /front[-\s]?end/i,
    /frontend/i,
    /web developer/i,
    /ui engineer/i,
    /javascript developer/i,
  ],
  'Backend Development': [
    /back[-\s]?end/i,
    /backend/i,
    /server engineer/i,
    /api developer/i,
    /platform engineer/i,
  ],
  'Full Stack Development': [/full[-\s]?stack/i, /fullstack/i],
  'Mobile Development': [
    /mobile/i,
    /\bios\b/i,
    /android/i,
    /react native/i,
    /swift/i,
    /kotlin/i,
  ],
  'Machine Learning': [
    /machine learning/i,
    /\bml\b/i,
    /deep learning/i,
    /computer vision/i,
    /artificial intelligence/i,
  ],
  'Data Science': [
    /data science/i,
    /data scientist/i,
    /data analytics/i,
    /data analyst/i,
    /business intelligence/i,
  ],
  'Data Engineering': [
    /data engineer/i,
    /data engineering/i,
    /analytics engineer/i,
    /data platform/i,
    /data pipeline/i,
  ],
  'Quantitative Finance': [
    /quantitative/i,
    /\bquant\b/i,
    /algorithmic trading/i,
    /trading analyst/i,
    /derivatives/i,
    /quant finance/i,
  ],
  'Research': [
    /research scientist/i,
    /research engineer/i,
    /research internship/i,
    /r&d/i,
  ],
  'Security Engineering': [
    /security engineer/i,
    /cybersecurity/i,
    /information security/i,
    /appsec/i,
  ],
  'DevOps': [
    /devops/i,
    /site reliability/i,
    /\bsre\b/i,
    /infrastructure/i,
    /cloud engineer/i,
    /platform reliability/i,
    /release engineer/i,
  ],
  'Quality Assurance': [
    /\bqa\b/i,
    /quality assurance/i,
    /test engineer/i,
    /testing engineer/i,
    /automation engineer/i,
  ],
  'Hardware Engineering': [
    /hardware engineer/i,
    /electrical engineer/i,
    /electronics engineer/i,
    /asic/i,
    /fpga/i,
    /semiconductor/i,
    /chip design/i,
  ],
  'Embedded Systems': [
    /embedded engineer/i,
    /embedded systems/i,
    /firmware/i,
    /\biot\b/i,
    /real-time systems/i,
  ],
  'Robotics': [
    /robotics/i,
    /robotic engineer/i,
    /autonomous systems/i,
    /mechatronics/i,
  ],
  'Product Management': [
    /product manager/i,
    /product management/i,
    /product strategy/i,
  ],
  'UI/UX Design': [
    /user experience/i,
    /user interface/i,
    /ux design/i,
    /ui design/i,
    /product design/i,
    /interaction design/i,
  ],
};
