export interface Internship {
  id: string;
  company_name: string;
  position_title: string;
  description: string;
  job_type: string;
  location: string;
  eligible_years: string[];
  posted_date: string;
  application_deadline: string | null;
  application_url: string;
  is_active: boolean;
  created_at: string;
}

export const mockInternships: Internship[] = [
  {
    id: '1',
    company_name: 'Google',
    position_title: 'Software Engineering Intern',
    description: 'Work on cutting-edge projects in cloud computing, machine learning, and distributed systems. Collaborate with experienced engineers on products used by billions.',
    job_type: 'Software Engineering',
    location: 'Mountain View, CA',
    eligible_years: ['Junior', 'Senior', 'Graduate'],
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    application_deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    application_url: 'https://careers.google.com/jobs',
    is_active: true,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    company_name: 'Meta',
    position_title: 'Data Science Intern',
    description: 'Analyze large-scale data sets to drive product decisions. Work with cross-functional teams to identify trends and insights.',
    job_type: 'Data Science',
    location: 'Menlo Park, CA',
    eligible_years: ['Junior', 'Senior', 'Graduate'],
    posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    application_deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    application_url: 'https://www.metacareers.com/',
    is_active: true,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    company_name: 'Microsoft',
    position_title: 'Software Engineering Intern - Azure',
    description: 'Build scalable cloud services and infrastructure. Learn from industry experts while contributing to Microsoft Azure.',
    job_type: 'Software Engineering',
    location: 'Redmond, WA',
    eligible_years: ['Sophomore', 'Junior', 'Senior'],
    posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    application_deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    application_url: 'https://careers.microsoft.com/',
    is_active: true,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    company_name: 'Amazon',
    position_title: 'Machine Learning Intern',
    description: 'Develop and deploy ML models at scale. Work on recommendation systems, natural language processing, and computer vision.',
    job_type: 'Machine Learning',
    location: 'Seattle, WA',
    eligible_years: ['Junior', 'Senior', 'Graduate'],
    posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    application_deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    application_url: 'https://www.amazon.jobs/',
    is_active: true,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    company_name: 'Stripe',
    position_title: 'Software Engineering Intern',
    description: 'Build payment infrastructure for the internet. Work on APIs, financial systems, and developer tools.',
    job_type: 'Software Engineering',
    location: 'San Francisco, CA',
    eligible_years: ['Junior', 'Senior'],
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    application_deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
    application_url: 'https://stripe.com/jobs',
    is_active: true,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    company_name: 'Airbnb',
    position_title: 'Product Management Intern',
    description: 'Drive product strategy and roadmap. Work with engineering, design, and data teams to build features for millions of users.',
    job_type: 'Product Management',
    location: 'San Francisco, CA',
    eligible_years: ['Junior', 'Senior', 'Graduate'],
    posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    application_deadline: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000).toISOString(),
    application_url: 'https://careers.airbnb.com/',
    is_active: true,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '7',
    company_name: 'Tesla',
    position_title: 'Mobile Development Intern',
    description: 'Build iOS and Android applications for Tesla vehicles and energy products. Work on cutting-edge automotive technology.',
    job_type: 'Mobile Development',
    location: 'Palo Alto, CA',
    eligible_years: ['Sophomore', 'Junior', 'Senior'],
    posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    application_deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    application_url: 'https://www.tesla.com/careers',
    is_active: true,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '8',
    company_name: 'Cloudflare',
    position_title: 'Security Engineering Intern',
    description: 'Protect and accelerate the internet. Work on DDoS mitigation, zero-trust security, and network infrastructure.',
    job_type: 'Security Engineering',
    location: 'Remote',
    eligible_years: ['Junior', 'Senior', 'Graduate'],
    posted_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    application_deadline: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000).toISOString(),
    application_url: 'https://www.cloudflare.com/careers/',
    is_active: true,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '9',
    company_name: 'Netflix',
    position_title: 'DevOps Intern',
    description: 'Build and maintain infrastructure for streaming to 200+ million subscribers. Work with containers, Kubernetes, and cloud platforms.',
    job_type: 'DevOps',
    location: 'Los Gatos, CA',
    eligible_years: ['Junior', 'Senior'],
    posted_date: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    application_deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    application_url: 'https://jobs.netflix.com/',
    is_active: true,
    created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '10',
    company_name: 'Figma',
    position_title: 'UI/UX Design Intern',
    description: 'Design the future of collaborative design tools. Create beautiful, intuitive interfaces used by millions of designers.',
    job_type: 'UI/UX Design',
    location: 'San Francisco, CA',
    eligible_years: ['Sophomore', 'Junior', 'Senior'],
    posted_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    application_deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    application_url: 'https://www.figma.com/careers/',
    is_active: true,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '11',
    company_name: 'Shopify',
    position_title: 'Software Engineering Intern',
    description: 'Build commerce infrastructure for millions of entrepreneurs. Work on Ruby on Rails, React, and GraphQL.',
    job_type: 'Software Engineering',
    location: 'Remote',
    eligible_years: ['Sophomore', 'Junior', 'Senior', 'Graduate'],
    posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    application_deadline: null,
    application_url: 'https://www.shopify.com/careers',
    is_active: true,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '12',
    company_name: 'Notion',
    position_title: 'Software Engineering Intern',
    description: 'Build the all-in-one workspace. Create features that help teams collaborate and stay organized.',
    job_type: 'Software Engineering',
    location: 'San Francisco, CA',
    eligible_years: ['Junior', 'Senior'],
    posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    application_deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    application_url: 'https://www.notion.so/careers',
    is_active: true,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
